language: go
sudo: false
env:
  - GO111MODULE=on
go:
  - 1.12.x
install:
  - go mod download
#  - go install github.com/golang/lint/golint
script:
  - diff <(gofmt -d .) <(echo -n)
  - go vet -x ./...
  #  - golint -set_exit_status ./...
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)