name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go
    - name: Set up GoLint
      run: go get -u golang.org/x/lint/golint
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Get dependencies
      run: go get -v -t -d ./...
    - name: Build
      run: go build -v .
    - name: Format Test
      run: diff <(gofmt -d .) <(echo -n)
    - name: Run vet
      run: go vet -x ./...
    - name: Run GoLint
      run: $(go list -f {{.Target}} golang.org/x/lint/golint) -set_exit_status ./...
    - name: Test
      run: go test -v -race -coverprofile=coverage.txt -covermode=atomic
    - name: Codecov
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./coverage.txt
